MARGINS = [
    # SMARTPHONES & MOBILE
    ("SMARTPHONES & MOBILE", "iPhone (Current Gen)", 35, 45, "Latest models, excellent condition"),
    ("SMARTPHONES & MOBILE", "iPhone (1-2 Years)", 30, 40, "High demand"),
    ("SMARTPHONES & MOBILE", "iPhone (3-4 Years)", 20, 30, "Moderate demand"),
    ("SMARTPHONES & MOBILE", "iPhone (5+ Years)", 10, 20, "Declining value"),
    ("SMARTPHONES & MOBILE", "Samsung Galaxy (Flagship)", 30, 40, "S-series, Note series"),
    ("SMARTPHONES & MOBILE", "Samsung Galaxy (Mid-Range)", 20, 30, "A-series"),
    ("SMARTPHONES & MOBILE", "Samsung Galaxy (Budget/Old)", 10, 20, "Entry-level or 3+ years"),
    ("SMARTPHONES & MOBILE", "Google Pixel (Current)", 25, 35, "Latest models"),
    ("SMARTPHONES & MOBILE", "Google Pixel (Older)", 15, 25, "2+ years old"),
    ("SMARTPHONES & MOBILE", "Other Android Flagship", 20, 30, "OnePlus, Xiaomi, Sony"),
    ("SMARTPHONES & MOBILE", "Budget Android", 5, 15, "Under £200 retail"),
    ("SMARTPHONES & MOBILE", "AirPods Pro/Max", 30, 40, "Genuine, boxed, working"),
    ("SMARTPHONES & MOBILE", "Standard Earbuds", 15, 25, "Brand dependent"),

    # COMPUTING & TABLETS
    ("COMPUTING & TABLETS", "MacBook Pro (Current)", 35, 45, "M-series chips"),
    ("COMPUTING & TABLETS", "MacBook Pro (1-3 Years)", 30, 40, "Intel or M1/M2"),
    ("COMPUTING & TABLETS", "MacBook Air (Current)", 30, 40, "M-series"),
    ("COMPUTING & TABLETS", "MacBook (Older)", 20, 30, "4+ years, Intel"),
    ("COMPUTING & TABLETS", "Windows Gaming Laptop", 25, 35, "High-spec, RTX graphics"),
    ("COMPUTING & TABLETS", "Windows Business Laptop", 25, 35, "Dell XPS, ThinkPad, HP Spectre"),
    ("COMPUTING & TABLETS", "Windows Mid-Range Laptop", 20, 30, "Standard specs"),
    ("COMPUTING & TABLETS", "Windows Budget Laptop", 10, 20, "Low specs, older"),
    ("COMPUTING & TABLETS", "iPad Pro (Current)", 35, 45, "Latest models"),
    ("COMPUTING & TABLETS", "iPad Pro (Older)", 25, 35, "2-3 years"),
    ("COMPUTING & TABLETS", "iPad Air (Current)", 30, 40, "Popular model"),
    ("COMPUTING & TABLETS", "iPad Standard (Current)", 25, 35, "Entry-level"),
    ("COMPUTING & TABLETS", "iPad (Older)", 15, 25, "3+ years"),
    ("COMPUTING & TABLETS", "Samsung Tab (Premium)", 25, 35, "Tab S series"),
    ("COMPUTING & TABLETS", "Samsung Tab (Standard)", 15, 25, "Mid-range"),
    ("COMPUTING & TABLETS", "Amazon Fire Tablet", 5, 15, "Very low value"),
    ("COMPUTING & TABLETS", "Gaming PC (High-End)", 25, 35, "RTX 4000/3000"),
    ("COMPUTING & TABLETS", "Gaming PC (Mid-Range)", 20, 30, "Decent specs"),
    ("COMPUTING & TABLETS", "Standard Desktop", 10, 20, "Office/home use"),
    ("COMPUTING & TABLETS", "iMac (Recent)", 30, 40, "M-series"),

    # GAMING CONSOLES & ACCESSORIES
    ("GAMING CONSOLES & ACCESSORIES", "PlayStation 5", 35, 45, "Disc/Digital, high demand"),
    ("GAMING CONSOLES & ACCESSORIES", "PlayStation 4 Pro", 25, 35, "Still relevant"),
    ("GAMING CONSOLES & ACCESSORIES", "PlayStation 4 Standard", 20, 30, "Basic model"),
    ("GAMING CONSOLES & ACCESSORIES", "Xbox Series X", 35, 45, "Premium model"),
    ("GAMING CONSOLES & ACCESSORIES", "Xbox Series S", 30, 40, "Digital-only"),
    ("GAMING CONSOLES & ACCESSORIES", "Xbox One X", 20, 30, "Enhanced model"),
    ("GAMING CONSOLES & ACCESSORIES", "Xbox One S/Standard", 15, 25, "Basic models"),
    ("GAMING CONSOLES & ACCESSORIES", "Nintendo Switch OLED", 35, 45, "Premium, high demand"),
    ("GAMING CONSOLES & ACCESSORIES", "Nintendo Switch Standard", 30, 40, "Very popular"),
    ("GAMING CONSOLES & ACCESSORIES", "Nintendo Switch Lite", 25, 35, "Handheld-only"),
    ("GAMING CONSOLES & ACCESSORIES", "Retro Consoles", 15, 30, "Varies by rarity"),
    ("GAMING CONSOLES & ACCESSORIES", "Controllers (Official)", 25, 35, "Current gen"),
    ("GAMING CONSOLES & ACCESSORIES", "Controllers (Third-Party)", 10, 20, "Generic brands"),
    ("GAMING CONSOLES & ACCESSORIES", "VR Headsets (Current)", 30, 40, "PSVR2, Quest 3"),
    ("GAMING CONSOLES & ACCESSORIES", "VR Headsets (Older)", 15, 25, "PSVR1, Quest 1/2"),

    # VIDEO GAMES
    ("VIDEO GAMES", "AAA (Current Year)", 30, 40, "New releases"),
    ("VIDEO GAMES", "AAA (1-2 Years)", 20, 30, "Popular titles"),
    ("VIDEO GAMES", "AAA (3+ Years)", 10, 20, "Older releases"),
    ("VIDEO GAMES", "Nintendo First-Party", 25, 35, "Hold value well"),
    ("VIDEO GAMES", "Sports (Current Year)", 20, 30, "FIFA, NBA 2K"),
    ("VIDEO GAMES", "Sports (Previous Year)", 5, 15, "Rapid depreciation"),
    ("VIDEO GAMES", "Retro (Rare)", 20, 40, "Collectible"),
    ("VIDEO GAMES", "Retro (Common)", 5, 15, "Abundant supply"),

    # AUDIO EQUIPMENT
    ("AUDIO EQUIPMENT", "AirPods Max", 35, 45, "Premium Apple"),
    ("AUDIO EQUIPMENT", "AirPods Pro (Gen 2)", 30, 40, "Current model"),
    ("AUDIO EQUIPMENT", "AirPods (Standard)", 25, 35, "Gen 2/3"),
    ("AUDIO EQUIPMENT", "Sony WH-1000XM", 30, 40, "Flagship noise-cancelling"),
    ("AUDIO EQUIPMENT", "Bose QuietComfort", 30, 40, "Premium noise-cancelling"),
    ("AUDIO EQUIPMENT", "Beats (Premium)", 25, 35, "Studio, Solo Pro"),
    ("AUDIO EQUIPMENT", "Beats (Standard)", 20, 30, "Entry-level"),
    ("AUDIO EQUIPMENT", "Sonos Speakers", 30, 40, "Multi-room system"),
    ("AUDIO EQUIPMENT", "Bose SoundLink", 25, 35, "Portable Bluetooth"),
    ("AUDIO EQUIPMENT", "JBL (Premium)", 20, 30, "Charge, Flip series"),
    ("AUDIO EQUIPMENT", "Marshall Speakers", 25, 35, "Distinctive brand"),
    ("AUDIO EQUIPMENT", "Soundbars (Premium)", 25, 35, "Samsung, Sony, Bose"),
    ("AUDIO EQUIPMENT", "Soundbars (Standard)", 15, 25, "Mid-range"),

    # SMART WATCHES & WEARABLES
    ("SMART WATCHES & WEARABLES", "Apple Watch Ultra", 35, 45, "Premium model"),
    ("SMART WATCHES & WEARABLES", "Apple Watch Series 9/8", 30, 40, "Recent models"),
    ("SMART WATCHES & WEARABLES", "Apple Watch SE", 25, 35, "Mid-tier"),
    ("SMART WATCHES & WEARABLES", "Apple Watch (Older)", 20, 30, "Series 6/7 and older"),
    ("SMART WATCHES & WEARABLES", "Samsung Galaxy Watch (Latest)", 25, 35, "Premium models"),
    ("SMART WATCHES & WEARABLES", "Samsung Galaxy Watch (Older)", 15, 25, "Previous gen"),
    ("SMART WATCHES & WEARABLES", "Garmin (Premium)", 25, 35, "Fenix, Forerunner"),
    ("SMART WATCHES & WEARABLES", "Garmin (Standard)", 20, 30, "Mid-range fitness"),
    ("SMART WATCHES & WEARABLES", "Fitbit (Premium)", 20, 30, "Sense, Versa"),
    ("SMART WATCHES & WEARABLES", "Fitbit (Basic)", 10, 20, "Inspire, Charge"),

    # CAMERAS & PHOTOGRAPHY
    ("CAMERAS & PHOTOGRAPHY", "DSLR (Professional)", 25, 35, "Canon 5D, Nikon D850"),
    ("CAMERAS & PHOTOGRAPHY", "DSLR (Enthusiast)", 20, 30, "Canon 90D, Nikon D7500"),
    ("CAMERAS & PHOTOGRAPHY", "DSLR (Entry)", 15, 25, "Canon Rebel, Nikon D3500"),
    ("CAMERAS & PHOTOGRAPHY", "Mirrorless (Professional)", 30, 40, "Sony A7 IV, Canon R5/R6"),
    ("CAMERAS & PHOTOGRAPHY", "Mirrorless (Mid-Range)", 25, 35, "Fujifilm X-T, Sony A6000"),
    ("CAMERAS & PHOTOGRAPHY", "Mirrorless (Entry)", 20, 30, "Canon M-series"),
    ("CAMERAS & PHOTOGRAPHY", "GoPro (Latest)", 25, 35, "Hero 11/12"),
    ("CAMERAS & PHOTOGRAPHY", "GoPro (Older)", 15, 25, "Hero 7-10"),
    ("CAMERAS & PHOTOGRAPHY", "DJI Drone (High-End)", 30, 40, "Mavic 3, Air 3"),
    ("CAMERAS & PHOTOGRAPHY", "DJI Drone (Mid-Range)", 25, 35, "Mini series"),
    ("CAMERAS & PHOTOGRAPHY", "Lenses (Professional)", 25, 35, "L-series, Gold Ring"),
    ("CAMERAS & PHOTOGRAPHY", "Lenses (Standard)", 15, 25, "Kit lenses"),

    # TELEVISIONS & DISPLAYS
    ("TELEVISIONS & DISPLAYS", "OLED (65+)", 25, 35, "LG, Sony high-end"),
    ("TELEVISIONS & DISPLAYS", "OLED (55\")", 25, 35, "Recent models"),
    ("TELEVISIONS & DISPLAYS", "QLED/Premium LED (65+)", 20, 30, "Samsung QLED"),
    ("TELEVISIONS & DISPLAYS", "QLED/Premium LED (55\")", 20, 30, "Mid-size premium"),
    ("TELEVISIONS & DISPLAYS", "4K Smart TV (Large 65+)", 15, 25, "Bulky transport"),
    ("TELEVISIONS & DISPLAYS", "4K Smart TV (Medium 43-55\")", 15, 25, "Most common"),
    ("TELEVISIONS & DISPLAYS", "4K Smart TV (Small <43\")", 10, 20, "Lower demand"),
    ("TELEVISIONS & DISPLAYS", "1080p TV", 5, 15, "Outdated"),
    ("TELEVISIONS & DISPLAYS", "Apple TV 4K", 25, 35, "Good demand"),
    ("TELEVISIONS & DISPLAYS", "Roku/Fire Stick", 15, 25, "Budget options"),

    # HOME ENTERTAINMENT
    ("HOME ENTERTAINMENT", "4K Blu-ray Player", 20, 30, "Premium models"),
    ("HOME ENTERTAINMENT", "Blu-ray Player", 10, 20, "Declining market"),
    ("HOME ENTERTAINMENT", "DVD Player", 5, 10, "Obsolete"),
    ("HOME ENTERTAINMENT", "4K Blu-rays", 25, 35, "New releases"),
    ("HOME ENTERTAINMENT", "Blu-rays", 15, 25, "General titles"),
    ("HOME ENTERTAINMENT", "DVDs (Box Sets)", 5, 15, "Complete sets"),
    ("HOME ENTERTAINMENT", "DVDs (Individual)", 2, 10, "Low value"),
    ("HOME ENTERTAINMENT", "Vinyl (Rare/Collectible)", 20, 40, "Condition critical"),
    ("HOME ENTERTAINMENT", "Vinyl (Standard)", 10, 20, "Common titles"),
    ("HOME ENTERTAINMENT", "CDs", 2, 10, "Very low demand"),

    # GOLD & JEWELRY
    ("GOLD & JEWELRY", "24K Gold", 85, 95, "Weight-based"),
    ("GOLD & JEWELRY", "22K Gold", 80, 90, "Weight-based"),
    ("GOLD & JEWELRY", "18K Gold", 75, 85, "Weight-based"),
    ("GOLD & JEWELRY", "14K Gold", 65, 75, "Weight-based"),
    ("GOLD & JEWELRY", "9K Gold", 50, 60, "Weight-based"),
    ("GOLD & JEWELRY", "Gold Coins (Bullion)", 85, 95, "Sovereigns, Krugerrands"),
    ("GOLD & JEWELRY", "Designer Jewelry (Tiffany/Cartier)", 40, 50, "Authenticated"),
    ("GOLD & JEWELRY", "Diamond (Certified)", 30, 40, "GIA certified"),
    ("GOLD & JEWELRY", "Diamond (Uncertified)", 20, 30, "No papers"),
    ("GOLD & JEWELRY", "Silver (Sterling)", 40, 60, "Weight-based"),
    ("GOLD & JEWELRY", "Rolex (Authenticated)", 50, 70, "High-value"),
    ("GOLD & JEWELRY", "Omega (Authenticated)", 40, 50, "Luxury"),
    ("GOLD & JEWELRY", "Tag Heuer", 35, 45, "Premium"),
    ("GOLD & JEWELRY", "Other Luxury Watches", 30, 40, "Breitling, IWC"),

    # TOOLS & DIY
    ("TOOLS & DIY", "Cordless Drill (Premium)", 25, 35, "DeWalt, Milwaukee, Makita"),
    ("TOOLS & DIY", "Cordless Drill (Standard)", 20, 30, "Bosch, Ryobi"),
    ("TOOLS & DIY", "Tool Combo Kits", 25, 35, "Multiple tools, batteries"),
    ("TOOLS & DIY", "Corded Power Tools", 15, 25, "Less desirable"),
    ("TOOLS & DIY", "Tool Sets (Complete)", 20, 30, "Socket, spanner sets"),
    ("TOOLS & DIY", "Petrol Lawnmower", 15, 25, "Serviced"),
    ("TOOLS & DIY", "Electric Lawnmower", 15, 25, "Good condition"),
    ("TOOLS & DIY", "Pressure Washer (Karcher)", 20, 30, "Popular brand"),

    # SMALL APPLIANCES
    ("SMALL APPLIANCES", "Coffee Machine (Premium)", 20, 30, "De'Longhi, Sage, Nespresso"),
    ("SMALL APPLIANCES", "Air Fryer (Premium)", 20, 30, "Ninja, Philips"),
    ("SMALL APPLIANCES", "Air Fryer (Standard)", 15, 25, "Popular item"),
    ("SMALL APPLIANCES", "Vacuum (Dyson)", 25, 35, "Cordless models"),
    ("SMALL APPLIANCES", "Vacuum (Shark)", 20, 30, "Popular alternative"),
    ("SMALL APPLIANCES", "Robot Vacuum (Premium)", 25, 35, "Roomba, Roborock"),
    ("SMALL APPLIANCES", "Hair Dryer (Dyson)", 30, 40, "Supersonic"),
    ("SMALL APPLIANCES", "Hair Straightener (GHD)", 20, 30, "Popular brand"),
    ("SMALL APPLIANCES", "Electric Toothbrush", 15, 25, "Oral-B, Sonicare"),

    ("MUSICAL INSTRUMENTS", "Electric Guitar (Premium)", 30, 40, "Fender, Gibson"),
    ("MUSICAL INSTRUMENTS", "Electric Guitar (Mid)", 25, 35, "Squier, Epiphone"),
    ("MUSICAL INSTRUMENTS", "Acoustic Guitar (Premium)", 30, 40, "Martin, Taylor"),
    ("MUSICAL INSTRUMENTS", "Acoustic Guitar (Mid)", 20, 30, "Yamaha, Ibanez"),
    ("MUSICAL INSTRUMENTS", "Bass Guitar", 25, 35, "Fender, Music Man"),
    ("MUSICAL INSTRUMENTS", "Guitar Amp (Valve)", 25, 35, "Marshall, Fender"),
    ("MUSICAL INSTRUMENTS", "Digital Piano", 25, 35, "Yamaha, Roland, 88 keys"),
    ("MUSICAL INSTRUMENTS", "Synthesizer", 25, 35, "Korg, Moog, Roland"),
    ("MUSICAL INSTRUMENTS", "Electronic Drum Kit", 25, 35, "Roland, Alesis"),
    ("MUSICAL INSTRUMENTS", "DJ Controller", 25, 35, "Pioneer, Native Instruments"),

    # SPORTS & FITNESS
    ("SPORTS & FITNESS", "Golf Clubs (Premium Set)", 25, 35, "Titleist, Callaway"),
    ("SPORTS & FITNESS", "Golf Clubs (Individual)", 15, 25, "Quality brands"),
    ("SPORTS & FITNESS", "Bicycle (Road/Mountain)", 20, 30, "Quality brands"),
    ("SPORTS & FITNESS", "Electric Scooter", 20, 30, "Xiaomi, Segway"),
    ("SPORTS & FITNESS", "Exercise Bike", 15, 25, "Peloton premium"),
    ("SPORTS & FITNESS", "Weights/Dumbbells", 20, 30, "Per kg pricing"),

    # MISCELLANEOUS
    ("MISCELLANEOUS", "Designer Handbag", 40, 50, "LV, Gucci (authenticated)"),
    ("MISCELLANEOUS", "Designer Sunglasses", 25, 35, "Ray-Ban, Oakley"),
    ("MISCELLANEOUS", "Pram (Premium)", 20, 30, "Bugaboo, iCandy"),
    ("MISCELLANEOUS", "Trading Cards (Rare)", 20, 40, "Pokemon, Magic, graded"),
    ("MISCELLANEOUS", "Action Figures (Boxed)", 20, 35, "Vintage, mint"),
]