# Generated by Django 5.2.7 on 2025-10-16 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='competitorlisting',
            old_name='timestamp',
            new_name='last_seen',
        ),
        migrations.AddField(
            model_name='competitorlisting',
            name='condition',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='competitorlisting',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='competitorlisting',
            name='stable_id',
            field=models.CharField(db_index=True, default='default', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='competitorlisting',
            unique_together={('competitor', 'stable_id')},
        ),
        migrations.CreateModel(
            name='CompetitorListingHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('title', models.CharField(max_length=255)),
                ('condition', models.CharField(blank=True, max_length=255, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='pricing.competitorlisting')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
