# Generated by Django 5.2.7 on 2025-10-29 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='itemmodel',
            unique_together={('subcategory', 'name')},
        ),
        migrations.AddField(
            model_name='subcategory',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='pricing.category'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='itemmodel',
            name='category',
        ),
    ]
