# Generated by Django 5.2.7 on 2025-10-30 10:21

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0002_alter_itemmodel_unique_together_subcategory_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='scrape_sources',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('CeX', 'CeX'), ('eBay', 'eBay'), ('CashConverters', 'CashConverters'), ('CashGenerator', 'CashGenerator')], help_text='Select which competitor sites to scrape for this category.', max_length=200),
        ),
    ]
