# Generated by Django 5.2.7 on 2025-10-17 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0002_rename_timestamp_competitorlisting_last_seen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketitem',
            name='last_scraped',
            field=models.DateTimeField(blank=True, help_text='Last time competitor listings were updated', null=True),
        ),
    ]
