# Generated by Django 5.2.6 on 2025-10-02 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0002_condition'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='condition',
            options={},
        ),
        migrations.RenameField(
            model_name='condition',
            old_name='is_active',
            new_name='active',
        ),
        migrations.AlterUniqueTogether(
            name='condition',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='condition',
            name='adjustment',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='condition',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.RemoveField(
            model_name='condition',
            name='category',
        ),
    ]
