# Generated by Django 5.2.6 on 2025-10-02 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0003_alter_condition_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalMarginRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_type', models.CharField(choices=[('manufacturer', 'Manufacturer'), ('model', 'Model'), ('condition', 'Condition'), ('demand', 'Demand'), ('feature', 'Feature')], max_length=20)),
                ('match_value', models.CharField(max_length=100)),
                ('adjustment', models.FloatField(help_text='e.g. 0.10 for +10%, -0.05 for -5%')),
                ('description', models.CharField(blank=True, max_length=200)),
                ('order', models.IntegerField(default=0, help_text='Rules with lower order run first')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', 'rule_type'],
            },
        ),
        migrations.DeleteModel(
            name='Condition',
        ),
    ]
