# Generated by Django 5.2.7 on 2025-10-17 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0003_marketitem_last_scraped'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='attributes',
            new_name='metadata',
        ),
        migrations.AddField(
            model_name='marketitem',
            name='attributes',
            field=models.JSONField(blank=True, help_text='Stores user-provided attribute values', null=True),
        ),
        migrations.AddField(
            model_name='marketitem',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='market_items', to='pricing.category'),
        ),
        migrations.AlterField(
            model_name='marketitem',
            name='exclude_keywords',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='marketitem',
            name='last_scraped',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='competitorlisting',
            unique_together={('market_item', 'competitor', 'stable_id')},
        ),
        migrations.CreateModel(
            name='CategoryAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Internal attribute name, e.g. 'storage'", max_length=100)),
                ('label', models.CharField(help_text="Field label shown to users, e.g. 'Storage Capacity'", max_length=255)),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('select', 'Select'), ('boolean', 'Boolean')], max_length=20)),
                ('required', models.BooleanField(default=True)),
                ('options', models.JSONField(blank=True, help_text="Required if field_type is 'select'. Example: ['64GB','128GB','256GB']", null=True)),
                ('order', models.IntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='pricing.category')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('category', 'name')},
            },
        ),
        migrations.CreateModel(
            name='MarketItemAttributeValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_text', models.CharField(blank=True, max_length=255, null=True)),
                ('value_number', models.FloatField(blank=True, null=True)),
                ('value_boolean', models.BooleanField(default=False)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pricing.categoryattribute')),
                ('market_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attribute_values', to='pricing.marketitem')),
            ],
            options={
                'unique_together': {('market_item', 'attribute')},
            },
        ),
    ]
