# Generated by Django 5.2.6 on 2025-10-02 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0004_globalmarginrule_delete_condition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marginrule',
            name='rule_type',
            field=models.CharField(choices=[('manufacturer', 'Manufacturer'), ('model', 'Model'), ('condition', 'Condition'), ('feature', 'Feature')], max_length=20),
        ),
    ]
