# Generated by Django 5.2.7 on 2025-10-30 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0004_category_cex_discount_pct_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CEXPricingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cex_pct', models.FloatField(help_text='Percentage of CEX price to sell at, e.g., 0.8 for 80%')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cex_rules', to='pricing.category')),
                ('item_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cex_rules', to='pricing.itemmodel')),
                ('subcategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cex_rules', to='pricing.subcategory')),
            ],
            options={
                'ordering': ['category', 'subcategory', 'item_model', 'order'],
                'unique_together': {('category', 'subcategory', 'item_model')},
            },
        ),
    ]
