# Generated by Django 5.2.7 on 2025-10-17 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0004_rename_attributes_category_metadata_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='categoryattribute',
            name='field_type',
            field=models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('select', 'Select'), ('boolean', 'Boolean'), ('manufacturer', 'Manufacturer'), ('model', 'Model')], max_length=20),
        ),
        migrations.AlterField(
            model_name='categoryattribute',
            name='options',
            field=models.JSONField(blank=True, help_text="Required if field_type is 'select'. Example: ['64GB','128GB']", null=True),
        ),
        migrations.AddField(
            model_name='marketitemattributevalue',
            name='value_lookup',
            field=models.ForeignKey(blank=True, help_text='Used for manufacturer/model field types', null=True, on_delete=django.db.models.deletion.SET_NULL, to='pricing.manufacturer'),
        ),
        migrations.CreateModel(
            name='ItemModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='pricing.category')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='pricing.manufacturer')),
            ],
            options={
                'unique_together': {('category', 'manufacturer', 'name')},
            },
        ),
    ]
