# Generated by Django 5.2.6 on 2025-10-02 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0005_alter_marginrule_rule_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalmarginrule',
            name='rule_type',
            field=models.CharField(choices=[('condition', 'Condition'), ('demand', 'Demand')], max_length=20),
        ),
    ]
