# Generated by Django 5.2.7 on 2025-10-31 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0005_cexpricingrule'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cexpricingrule',
            options={'ordering': ['category', 'subcategory', 'item_model']},
        ),
        migrations.RemoveField(
            model_name='cexpricingrule',
            name='order',
        ),
        migrations.DeleteModel(
            name='PriceAnalysis',
        ),
    ]
