# Generated by Django 5.2.7 on 2025-10-17 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('pricing', '0005_manufacturer_alter_categoryattribute_field_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marketitemattributevalue',
            name='value_lookup',
        ),
        migrations.AddField(
            model_name='marketitemattributevalue',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='marketitemattributevalue',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
