# Generated by Django 5.2.7 on 2025-10-31 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0006_alter_cexpricingrule_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketitem',
            name='cex_cash_trade_price',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
