# Generated by Django 5.2.6 on 2025-10-02 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0006_alter_globalmarginrule_rule_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='globalmarginrule',
            options={},
        ),
        migrations.RemoveField(
            model_name='globalmarginrule',
            name='order',
        ),
    ]
