# Generated by Django 5.2.7 on 2025-10-17 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0006_remove_marketitemattributevalue_value_lookup_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marketitem',
            name='attributes',
        ),
        migrations.RemoveField(
            model_name='marketitemattributevalue',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='marketitemattributevalue',
            name='object_id',
        ),
        migrations.AddField(
            model_name='marketitem',
            name='manufacturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='market_items', to='pricing.manufacturer'),
        ),
        migrations.AddField(
            model_name='marketitem',
            name='model',
            field=models.ForeignKey(blank=True, help_text='Will be filtered by category + manufacturer', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='market_items', to='pricing.itemmodel'),
        ),
        migrations.AlterField(
            model_name='categoryattribute',
            name='field_type',
            field=models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('select', 'Select'), ('boolean', 'Boolean')], max_length=20),
        ),
        migrations.AlterField(
            model_name='categoryattribute',
            name='label',
            field=models.CharField(help_text="e.g. 'Storage Capacity'", max_length=255),
        ),
        migrations.AlterField(
            model_name='categoryattribute',
            name='name',
            field=models.CharField(help_text="e.g. 'storage'", max_length=100),
        ),
        migrations.AlterField(
            model_name='categoryattribute',
            name='options',
            field=models.JSONField(blank=True, help_text="For 'select' type: ['64GB','128GB']", null=True),
        ),
    ]
