# Generated by Django 5.2.7 on 2025-10-31 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0007_marketitem_cex_cash_trade_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketitem',
            name='cex_cash_trade_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
