# Generated by Django 5.2.7 on 2025-10-08 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0007_alter_globalmarginrule_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='priceanalysis',
            name='cost_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
