# Generated by Django 5.2.7 on 2025-10-22 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0008_rename_marketitemattributevalue_itemmodelattributevalue_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='marginrule',
            name='match_value_manufacturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pricing.manufacturer'),
        ),
    ]
