# Generated by Django 5.2.7 on 2025-10-31 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0008_alter_marketitem_cex_cash_trade_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketitem',
            name='cex_sale_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
