# Generated by Django 5.2.7 on 2025-10-14 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0008_priceanalysis_cost_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListingSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('cost_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('user_margin', models.DecimalField(decimal_places=2, default=37.5, max_digits=5)),
                ('market_range', models.CharField(blank=True, max_length=50)),
                ('market_average', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cex_avg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cex_discounted', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('rrp_with_margin', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cc_lowest', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cc_avg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cg_lowest', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cg_avg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cc_recommended_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cg_recommended_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('reasoning', models.TextField(blank=True)),
                ('competitors', models.JSONField(blank=True, default=list)),
                ('branch', models.CharField(blank=True, max_length=255)),
                ('listing_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='WebListing',
        ),
    ]
