# Generated by Django 5.2.7 on 2025-10-31 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0009_marketitem_cex_sale_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketitem',
            name='cex_url',
            field=models.CharField(blank=True, max_length=1048, null=True),
        ),
    ]
