# Generated by Django 5.2.7 on 2025-10-23 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0009_marginrule_match_value_manufacturer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marginrule',
            name='match_value_manufacturer',
        ),
        migrations.AlterField(
            model_name='marginrule',
            name='rule_type',
            field=models.CharField(choices=[('manufacturer', 'Manufacturer'), ('model', 'Model')], max_length=20),
        ),
    ]
