# Generated by Django 5.2.7 on 2025-11-05 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0010_marketitem_cex_url'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='marketitem',
            unique_together={('category', 'title')},
        ),
    ]
