# Generated by Django 5.2.7 on 2025-11-08 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0011_alter_marketitem_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitorlisting',
            name='trade_cash_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='competitorlisting',
            name='trade_voucher_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='competitorlistinghistory',
            name='trade_cash_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='competitorlistinghistory',
            name='trade_voucher_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
