# Generated by Django 5.2.7 on 2025-11-09 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0012_competitorlisting_trade_cash_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marketitem',
            name='cex_cash_trade_price',
        ),
        migrations.RemoveField(
            model_name='marketitem',
            name='cex_sale_price',
        ),
        migrations.RemoveField(
            model_name='marketitem',
            name='cex_url',
        ),
    ]
