# Generated by Django 5.2.7 on 2025-11-09 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0013_remove_marketitem_cex_cash_trade_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='cex_discount_pct',
        ),
    ]
