# Generated by Django 5.2.7 on 2025-11-11 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0014_remove_category_cex_discount_pct'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='marketitem',
            unique_together={('category', 'title', 'item_model')},
        ),
    ]
