# Generated by Django 5.2.7 on 2025-11-13 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0015_alter_marketitem_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cexpricingrule',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cex_rules', to='pricing.category'),
        ),
    ]
