# Generated by Django 5.2.7 on 2025-11-17 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0016_alter_cexpricingrule_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='cexpricingrule',
            name='cex_buying_pct',
            field=models.FloatField(default=0.9, help_text="Percentage of CEX cash offer to offer in case our calculated offer is lower than CEX's"),
            preserve_default=False,
        ),
    ]
