# Generated by Django 5.2.7 on 2025-11-17 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0017_cexpricingrule_cex_buying_pct'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cexpricingrule',
            options={'ordering': ['category', 'subcategory', 'item_model', 'movement_class']},
        ),
        migrations.AlterUniqueTogether(
            name='cexpricingrule',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='cexpricingrule',
            name='movement_class',
            field=models.CharField(choices=[('slow', 'Slow Moving'), ('medium', 'Medium Moving'), ('fast', 'Fast Moving')], default='medium', max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='cexpricingrule',
            unique_together={('category', 'subcategory', 'item_model', 'movement_class')},
        ),
    ]
