# Generated by Django 5.2.7 on 2025-11-17 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0018_alter_cexpricingrule_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cexpricingrule',
            name='cex_buying_pct',
        ),
    ]
