# Generated by Django 5.2.7 on 2025-11-17 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0019_remove_cexpricingrule_cex_buying_pct'),
    ]

    operations = [
        migrations.CreateModel(
            name='CEXPricingRuleGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pricing.category')),
                ('item_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pricing.itemmodel')),
                ('subcategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pricing.subcategory')),
            ],
            options={
                'verbose_name': 'Pricing Rule Bundle',
                'verbose_name_plural': 'Pricing Rule Bundles',
            },
        ),
        migrations.AddField(
            model_name='cexpricingrule',
            name='rule_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='pricing.cexpricingrulegroup'),
        ),
    ]
