# Generated by Django 5.2.7 on 2025-11-17 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0020_cexpricingrulegroup_cexpricingrule_rule_group'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cexpricingrule',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='cexpricingrule',
            constraint=models.UniqueConstraint(fields=('category', 'subcategory', 'item_model', 'movement_class'), name='unique_rule_per_scope_and_movement'),
        ),
    ]
