# Generated by Django 5.2.7 on 2025-11-17 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0021_alter_cexpricingrule_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cexpricingrule',
            name='rule_group',
        ),
        migrations.DeleteModel(
            name='CEXPricingRuleGroup',
        ),
    ]
