# Generated by Django 5.2.7 on 2026-01-07 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0022_remove_cexpricingrule_rule_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemmodel',
            name='name',
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
