# Generated by Django 5.2.7 on 2026-01-13 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0023_alter_itemmodel_name'),
    ]

    operations = [
    migrations.RemoveField(
        model_name='itemmodelattributevalue',
        name='attribute',
    ),
    migrations.RemoveField(
        model_name='itemmodelattributevalue',
        name='item_model',
    ),
    migrations.AlterField(
        model_name='itemmodel',
        name='name',
        field=models.CharField(max_length=100),
    ),
    migrations.DeleteModel(
        name='CategoryAttribute',
    ),
    migrations.DeleteModel(
        name='ItemModelAttributeValue',
    ),
]
