# Generated by Django 5.2.7 on 2026-01-13 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0024_remove_itemmodelattributevalue_attribute_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="e.g. 'storage'", max_length=100)),
                ('label', models.CharField(help_text="e.g. 'Storage Capacity'", max_length=255)),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('select', 'Select'), ('boolean', 'Boolean')], max_length=20)),
                ('required', models.BooleanField(default=True)),
                ('options', models.JSONField(blank=True, help_text="For 'select' type: ['64GB','128GB']", null=True)),
                ('order', models.IntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='pricing.category')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('category', 'name')},
            },
        ),
        migrations.CreateModel(
            name='ItemModelAttributeValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_text', models.CharField(blank=True, max_length=255, null=True)),
                ('value_number', models.FloatField(blank=True, null=True)),
                ('value_boolean', models.BooleanField(default=False)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pricing.categoryattribute')),
                ('item_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attribute_values', to='pricing.itemmodel')),
            ],
            options={
                'unique_together': {('item_model', 'attribute')},
            },
        ),
    ]
