# Generated by Django 5.2.7 on 2026-01-15 10:25

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0025_categoryattribute_itemmodelattributevalue'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('attribute_id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, help_text="Attribute code (e.g., 'storage_tb', 'edition')", max_length=100)),
            ],
            options={
                'db_table': 'pricing_attribute',
            },
        ),
        migrations.CreateModel(
            name='ConditionGrade',
            fields=[
                ('condition_grade_id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, help_text="Condition code (e.g., 'BOXED', 'UNBOXED', 'DISCOUNTED')", max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Condition Grade',
                'verbose_name_plural': 'Condition Grades',
                'db_table': 'pricing_condition_grade',
            },
        ),
        migrations.CreateModel(
            name='AttributeValue',
            fields=[
                ('attribute_value_id', models.AutoField(primary_key=True, serialize=False)),
                ('value', models.CharField(db_index=True, max_length=255)),
                ('attribute', models.ForeignKey(db_column='attribute_id', on_delete=django.db.models.deletion.CASCADE, related_name='values', to='pricing.attribute')),
            ],
            options={
                'db_table': 'pricing_attribute_value',
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('parent_category', models.ForeignKey(db_column='parent_category_id', help_text='Parent category. Root categories point to themselves.', on_delete=django.db.models.deletion.CASCADE, related_name='children', to='pricing.productcategory')),
            ],
            options={
                'verbose_name': 'Product Category',
                'verbose_name_plural': 'Product Categories',
                'db_table': 'pricing_product_category',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('category', models.ForeignKey(db_column='category_id', on_delete=django.db.models.deletion.CASCADE, related_name='products', to='pricing.productcategory')),
            ],
            options={
                'db_table': 'pricing_product',
            },
        ),
        migrations.AddField(
            model_name='attribute',
            name='category',
            field=models.ForeignKey(db_column='category_id', on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='pricing.productcategory'),
        ),
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('variant_id', models.AutoField(primary_key=True, serialize=False)),
                ('cex_sku', models.CharField(db_index=True, help_text='CeX SKU - stable identity', max_length=100, unique=True)),
                ('current_price_gbp', models.DecimalField(decimal_places=2, help_text='Current price in GBP (denormalized for fast reads)', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('variant_signature', models.CharField(db_index=True, help_text="Unique signature encoding attribute values (e.g., 'storage=1TB|edition=Digital')", max_length=500)),
                ('condition_grade', models.ForeignKey(db_column='condition_grade_id', on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='pricing.conditiongrade')),
                ('product', models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='pricing.product')),
            ],
            options={
                'db_table': 'pricing_variant',
            },
        ),
        migrations.CreateModel(
            name='VariantAttributeValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute_value', models.ForeignKey(db_column='attribute_value_id', on_delete=django.db.models.deletion.CASCADE, related_name='variant_attribute_values', to='pricing.attributevalue')),
                ('variant', models.ForeignKey(db_column='variant_id', on_delete=django.db.models.deletion.CASCADE, related_name='variant_attribute_values', to='pricing.variant')),
            ],
            options={
                'db_table': 'pricing_variant_attribute_value',
            },
        ),
        migrations.AddField(
            model_name='variant',
            name='attribute_values',
            field=models.ManyToManyField(related_name='variants', through='pricing.VariantAttributeValue', to='pricing.attributevalue'),
        ),
        migrations.CreateModel(
            name='VariantPriceHistory',
            fields=[
                ('price_history_id', models.AutoField(primary_key=True, serialize=False)),
                ('price_gbp', models.DecimalField(decimal_places=2, help_text='Price in GBP at this point in time', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('recorded_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When this price was recorded')),
                ('variant', models.ForeignKey(db_column='variant_id', on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='pricing.variant')),
            ],
            options={
                'db_table': 'pricing_variant_price_history',
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='VariantStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('DELISTED', 'Delisted'), ('DISCONTINUED', 'Discontinued')], db_index=True, max_length=20)),
                ('effective_from', models.DateTimeField(db_index=True, help_text='When this status became effective')),
                ('variant', models.ForeignKey(db_column='variant_id', on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='pricing.variant')),
            ],
            options={
                'db_table': 'pricing_variant_status',
                'ordering': ['-effective_from'],
            },
        ),
        migrations.AddIndex(
            model_name='attributevalue',
            index=models.Index(fields=['attribute', 'value'], name='pricing_att_attribu_bc3a56_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='attributevalue',
            unique_together={('attribute', 'value')},
        ),
        migrations.AddIndex(
            model_name='productcategory',
            index=models.Index(fields=['parent_category', 'name'], name='pricing_pro_parent__ce1b9c_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category', 'name'], name='pricing_pro_categor_77fb0a_idx'),
        ),
        migrations.AddIndex(
            model_name='attribute',
            index=models.Index(fields=['category', 'code'], name='pricing_att_categor_3c8e4b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='attribute',
            unique_together={('category', 'code')},
        ),
        migrations.AddIndex(
            model_name='variantattributevalue',
            index=models.Index(fields=['variant', 'attribute_value'], name='pricing_var_variant_ad1da5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='variantattributevalue',
            unique_together={('variant', 'attribute_value')},
        ),
        migrations.AddIndex(
            model_name='variant',
            index=models.Index(fields=['product', 'condition_grade'], name='pricing_var_product_30cb23_idx'),
        ),
        migrations.AddIndex(
            model_name='variant',
            index=models.Index(fields=['cex_sku'], name='pricing_var_cex_sku_f003e7_idx'),
        ),
        migrations.AddIndex(
            model_name='variant',
            index=models.Index(fields=['current_price_gbp'], name='pricing_var_current_1173c8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='variant',
            unique_together={('product', 'condition_grade', 'variant_signature')},
        ),
        migrations.AddIndex(
            model_name='variantpricehistory',
            index=models.Index(fields=['variant', '-recorded_at'], name='pricing_var_variant_5b031b_idx'),
        ),
        migrations.AddIndex(
            model_name='variantpricehistory',
            index=models.Index(fields=['recorded_at'], name='pricing_var_recorde_fd7efe_idx'),
        ),
        migrations.AddIndex(
            model_name='variantstatus',
            index=models.Index(fields=['variant', '-effective_from'], name='pricing_var_variant_5d0c08_idx'),
        ),
        migrations.AddIndex(
            model_name='variantstatus',
            index=models.Index(fields=['status', 'effective_from'], name='pricing_var_status_339940_idx'),
        ),
    ]
