# Generated by Django 5.2.7 on 2026-01-18 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0026_attribute_conditiongrade_attributevalue_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='variant',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='variant',
            name='product',
            field=models.ForeignKey(blank=True, db_column='product_id', help_text='Product (nullable for raw scraped data)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='pricing.product'),
        ),
        migrations.AlterField(
            model_name='variant',
            name='variant_signature',
            field=models.CharField(blank=True, db_index=True, help_text="Unique signature encoding attribute values (e.g., 'storage=1TB|edition=Digital')", max_length=500, null=True),
        ),
    ]
