# Generated by Django 5.2.7 on 2026-01-18 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0027_alter_variant_unique_together_alter_variant_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='title',
            field=models.CharField(blank=True, db_index=True, help_text="Title from the listing (e.g., 'Xbox Console, Black, Unboxed')", max_length=500),
        ),
    ]
