# Generated by Django 5.2.7 on 2026-01-19 00:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0028_variant_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryRequirement',
            fields=[
                ('requirement_id', models.AutoField(primary_key=True, serialize=False)),
                ('attribute_name', models.CharField(db_index=True, help_text='Required attribute name', max_length=100)),
                ('is_skipped', models.BooleanField(default=False, help_text='True if user chose to skip this attribute (unlearnable)')),
            ],
            options={
                'verbose_name': 'Category Requirement',
                'verbose_name_plural': 'Category Requirements',
                'db_table': 'pricing_category_requirement',
            },
        ),
        migrations.CreateModel(
            name='CategorySkuPrefix',
            fields=[
                ('prefix_id', models.AutoField(primary_key=True, serialize=False)),
                ('prefix', models.CharField(db_index=True, help_text="SKU prefix (e.g., 'SPS5', 'SXB1')", max_length=20, unique=True)),
                ('sku_count', models.IntegerField(default=1, help_text='Number of SKUs used to compute this prefix')),
            ],
            options={
                'verbose_name': 'Category SKU Prefix',
                'verbose_name_plural': 'Category SKU Prefixes',
                'db_table': 'pricing_category_sku_prefix',
            },
        ),
        migrations.CreateModel(
            name='MatchRule',
            fields=[
                ('match_rule_id', models.AutoField(primary_key=True, serialize=False)),
                ('attribute_name', models.CharField(db_index=True, help_text="Attribute name (e.g., 'model_name', 'consoles_condition')", max_length=100)),
                ('attribute_value', models.CharField(db_index=True, help_text="The value this rule matches to (e.g., 'PlayStation 5 Pro', 'Boxed')", max_length=255)),
                ('match_pattern', models.JSONField(help_text='Match pattern - string for single match, list for multi-word match (all must appear)')),
                ('source_sku', models.CharField(blank=True, help_text="SKU this rule was learned from (or 'preloaded' for filter-based rules)", max_length=100, null=True)),
                ('source_title', models.CharField(blank=True, help_text='Title this rule was learned from', max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Match Rule',
                'verbose_name_plural': 'Match Rules',
                'db_table': 'pricing_match_rule',
            },
        ),
        migrations.AddField(
            model_name='productcategory',
            name='cex_category_id',
            field=models.IntegerField(blank=True, db_index=True, help_text='CeX API category ID (e.g., 810, 1063, 1143)', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='parent_category',
            field=models.ForeignKey(blank=True, db_column='parent_category_id', help_text='Parent category. Root categories point to themselves.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='pricing.productcategory'),
        ),
        migrations.AddIndex(
            model_name='productcategory',
            index=models.Index(fields=['cex_category_id'], name='pricing_pro_cex_cat_393bc2_idx'),
        ),
        migrations.AddField(
            model_name='categoryrequirement',
            name='category',
            field=models.ForeignKey(db_column='category_id', on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='pricing.productcategory'),
        ),
        migrations.AddField(
            model_name='categoryskuprefix',
            name='category',
            field=models.ForeignKey(db_column='category_id', on_delete=django.db.models.deletion.CASCADE, related_name='sku_prefixes', to='pricing.productcategory'),
        ),
        migrations.AddIndex(
            model_name='matchrule',
            index=models.Index(fields=['attribute_name'], name='pricing_mat_attribu_ecc72a_idx'),
        ),
        migrations.AddIndex(
            model_name='matchrule',
            index=models.Index(fields=['attribute_name', 'attribute_value'], name='pricing_mat_attribu_2316db_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='matchrule',
            unique_together={('attribute_name', 'attribute_value', 'match_pattern')},
        ),
        migrations.AddIndex(
            model_name='categoryrequirement',
            index=models.Index(fields=['category'], name='pricing_cat_categor_2de2e6_idx'),
        ),
        migrations.AddIndex(
            model_name='categoryrequirement',
            index=models.Index(fields=['category', 'attribute_name'], name='pricing_cat_categor_77cd1a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='categoryrequirement',
            unique_together={('category', 'attribute_name')},
        ),
        migrations.AddIndex(
            model_name='categoryskuprefix',
            index=models.Index(fields=['prefix'], name='pricing_cat_prefix_bcafcb_idx'),
        ),
        migrations.AddIndex(
            model_name='categoryskuprefix',
            index=models.Index(fields=['category'], name='pricing_cat_categor_f95c4b_idx'),
        ),
    ]
