# Generated by Django 5.2.7 on 2026-01-19 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0029_categoryrequirement_categoryskuprefix_matchrule_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryrequirement',
            name='always_fetch',
            field=models.BooleanField(
                default=False,
                help_text='True if this attribute is un-teachable and should always be fetched from the API for this category',
            ),
        ),
    ]

